name: UPDATE

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

permissions:
  contents: write  # Need write permission to push changes

jobs:
    update:
        runs-on: ubuntu-latest
        name: update data
        steps:
            - name: Checkout repo and submodules
              uses: actions/checkout@v4
              with:
                submodules: recursive
                fetch-depth: 0  # needed for full history and rebasing

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11.5'

            - name: Run update.py
              run: python update.py

            - name: Configure Git
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

            - uses: actions/checkout@v4
            - run: |
                git add .
                git commit -m "Update data"
                git push
