name: UPDATE

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

permissions:
  contents: write  # Need write permission to push changes

jobs:
    update:
        runs-on: ubuntu-latest
        name: update data
        steps:
            - name: Checkout repo and submodules
              uses: actions/checkout@v4
              with:
                submodules: recursive
                fetch-depth: 0
                token: ${{ secrets.GITHUB_TOKEN }} # Explicitly pass the token

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11.5'

            - name: Run update.py
              run: python update.py

            - name: Configure Git
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Push changes
              id: push_changes
              run: |
                CURRENT_BRANCH="${{ github.ref_name }}"

                if [[ -z "$(git status --porcelain)" ]]; then
                  echo "No changes to commit."
                  exit 0
                fi
                
                git add .
                git commit -m "Update data"
                git push origin HEAD:"${CURRENT_BRANCH}"
